FROM ubuntu:trusty
MAINTAINER Rasatavohary "zo@zonova.io"

# ---------
# NODEJS Installation
# ---------
RUN apt-get install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | sudo bash -
RUN apt-get upgrade -y
RUN nvm install 10

# ---------
# NPM update 
# ---------
RUN sudo apt-get install -y build-essential
RUN npm update

# ---------
# Deployd directory creation and setup
# ---------
RUN mkdir -p /app/src
RUN npm install -g deployd
WORKDIR /app/src
RUN dpd create deployd
WORKDIR /app/src/deployd
RUN dpd keygen
RUN dpd showkey

# ---------
# RUN Docker task of Deployd 
# ---------
CMD dpd -H ${MONGO_PORT_27017_TCP_ADDR} -P ${MONGO_PORT_27017_TCP_PORT} -d -n deployd
